# 6. 배열 입출력

In [1]:
import numpy as np

|함수 | 설명 | 파일 종류|
|:-----|:----:|:----:|
| ``np.save()``|Numpy 배열 객체 1개를 파일에 저장 | 바이너리|
| ``np.savez()``|Numpy 배열 객체 여러개를 파일에 저장 | 바이너리 |
| ``np.load() ``|Numpy 배열 저장 파일로부터 객체 로딩| 바이너리|
| ``np.loadtxt() ``|텍스트 파일로부터 배열 로딩| 텍스트 |
| ``np.savetxt() ``|텍스트 파일에 Numpy 배열 객체 저장| 텍스트  |

In [2]:
a2 = np.random.randint(1,10,size = (5,5))
print(a2)
np.save("a222", a2)

[[4 4 2 1 1]
 [7 1 3 6 6]
 [1 3 6 7 3]
 [2 6 9 2 9]
 [5 9 4 4 1]]


In [4]:
%ls    # a222라는 npy파일이 생김

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: EE2D-C31D

 C:\PythonFile\Python-basic\Numpy 디렉터리

2022-07-10  오후 10:36    <DIR>          .
2022-07-08  오후 10:18    <DIR>          ..
2022-07-10  오후 10:09    <DIR>          .ipynb_checkpoints
2022-07-10  오후 05:38           101,677 1. 배열 생성.ipynb
2022-07-09  오후 05:44            12,685 2. 배열 조회.ipynb
2022-07-09  오후 05:51            13,160 3. 배열 값 삽입,수정,삭제,복사.ipynb
2022-07-10  오후 10:19            23,982 4. 배열 변환.ipynb
2022-07-10  오후 10:33           223,163 5. 배열 연산.ipynb
2022-07-10  오후 10:34             1,957 6. 배열 입출력.ipynb
2022-07-10  오후 10:36               228 a222.npy
2022-07-08  오후 10:22           177,424 array예시.png
2022-07-10  오후 06:12            91,450 broadCasting 예시.png
2022-07-10  오후 09:18            24,448 interpolation method.png
              10개 파일             670,174 바이트
               3개 디렉터리  302,271,332,352 바이트 남음


In [6]:
b2 = np.random.randint(1,10,size = (5,5))
print(b2)
np.savez("ab222",a2,b2)

[[4 5 3 9 1]
 [6 7 9 8 4]
 [4 2 9 2 1]
 [7 4 5 8 3]
 [1 7 8 1 9]]


In [7]:
%ls        # 여러개라서 ab222.npz 라는 파일이 생김

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: EE2D-C31D

 C:\PythonFile\Python-basic\Numpy 디렉터리

2022-07-10  오후 10:37    <DIR>          .
2022-07-08  오후 10:18    <DIR>          ..
2022-07-10  오후 10:09    <DIR>          .ipynb_checkpoints
2022-07-10  오후 05:38           101,677 1. 배열 생성.ipynb
2022-07-09  오후 05:44            12,685 2. 배열 조회.ipynb
2022-07-09  오후 05:51            13,160 3. 배열 값 삽입,수정,삭제,복사.ipynb
2022-07-10  오후 10:19            23,982 4. 배열 변환.ipynb
2022-07-10  오후 10:33           223,163 5. 배열 연산.ipynb
2022-07-10  오후 10:36             4,328 6. 배열 입출력.ipynb
2022-07-10  오후 10:36               228 a222.npy
2022-07-10  오후 10:37               706 ab222.npz
2022-07-08  오후 10:22           177,424 array예시.png
2022-07-10  오후 06:12            91,450 broadCasting 예시.png
2022-07-10  오후 09:18            24,448 interpolation method.png
              11개 파일             673,251 바이트
               3개 디렉터리  302,268,354,560 바이트 남음


In [9]:
npy = np.load("a222.npy")
print(npy)

[[4 4 2 1 1]
 [7 1 3 6 6]
 [1 3 6 7 3]
 [2 6 9 2 9]
 [5 9 4 4 1]]


In [10]:
npz = np.load("ab222.npz")
print(npz.files)  # 여러개라서 .files

['arr_0', 'arr_1']


In [11]:
print(npz['arr_0'])     # a2
print(npz['arr_1'])     # b2

[[4 4 2 1 1]
 [7 1 3 6 6]
 [1 3 6 7 3]
 [2 6 9 2 9]
 [5 9 4 4 1]]
[[4 5 3 9 1]
 [6 7 9 8 4]
 [4 2 9 2 1]
 [7 4 5 8 3]
 [1 7 8 1 9]]


In [12]:
np.savetxt("a222.csv",a2, delimiter=',')   
# csv로 저장하고 구분자(delimiter)를 , 로 지정해주기 

In [33]:
!more a222.csv

4.000000000000000000e+00,4.000000000000000000e+00,2.000000000000000000e+00,1.000000000000000000e+00,1.000000000000000000e+00
7.000000000000000000e+00,1.000000000000000000e+00,3.000000000000000000e+00,6.000000000000000000e+00,6.000000000000000000e+00
1.000000000000000000e+00,3.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00,3.000000000000000000e+00
2.000000000000000000e+00,6.000000000000000000e+00,9.000000000000000000e+00,2.000000000000000000e+00,9.000000000000000000e+00
5.000000000000000000e+00,9.000000000000000000e+00,4.000000000000000000e+00,4.000000000000000000e+00,1.000000000000000000e+00


- 실수 형태를 텍스트 형태로 저장을 하기에 파일 열어보면 .0000000000 이런게 붙음 

In [36]:
# 옵션
np.savetxt("b222.csv",a2, delimiter=',', fmt = '%.1e',   # 소수점 1개만
          header = 'c1,c2,c3,c4,c5') 

In [37]:
!more b222.csv  

# c1,c2,c3,c4,c5
4.0e+00,4.0e+00,2.0e+00,1.0e+00,1.0e+00
7.0e+00,1.0e+00,3.0e+00,6.0e+00,6.0e+00
1.0e+00,3.0e+00,6.0e+00,7.0e+00,3.0e+00
2.0e+00,6.0e+00,9.0e+00,2.0e+00,9.0e+00
5.0e+00,9.0e+00,4.0e+00,4.0e+00,1.0e+00


- header도 생기고, 소수점도 한자리까지만 생김

In [14]:
np.savetxt("a222.txt",a2)

In [15]:
#np.savetxt("a2222.csv",a2)    # delimeter 지정 안하면 이상하게됨

In [18]:
csv = np.loadtxt("a222.csv", delimiter=',')  # 부를떄도 delimiter
csv

array([[4., 4., 2., 1., 1.],
       [7., 1., 3., 6., 6.],
       [1., 3., 6., 7., 3.],
       [2., 6., 9., 2., 9.],
       [5., 9., 4., 4., 1.]])